
import { UserRole } from '../types';

export const PERMISSIONS_MATRIX: Record<UserRole, Record<string, { visualizar: boolean; criar: boolean; editar: boolean; deletar: boolean; exportar: boolean }>> = {
  [UserRole.SUPER_ADMIN]: {
    dashboard: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    leads: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    clientes: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    servicos: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    visitas: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    propostas: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    vendas: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    projetos: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    execucoes: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    custos: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    financeiro: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    compras: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    estoque: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    posvenda: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    logs: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    bi_consolidated: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    segmentos: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    usuarios: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    notificacoes: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    sla_command: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    alertas: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true }
  },
  
  [UserRole.ADMIN]: {
    dashboard: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    leads: { visualizar: true, criar: true, editar: true, deletar: true, exportar: true },
    clientes: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    servicos: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    visitas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    propostas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    vendas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    projetos: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    execucoes: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    custos: { visualizar: true, criar: false, editar: true, deletar: false, exportar: true },
    financeiro: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    compras: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    estoque: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    posvenda: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    logs: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    bi_consolidated: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    segmentos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    usuarios: { visualizar: true, criar: true, editar: true, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    sla_command: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    alertas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: true }
  },
  
  [UserRole.GERENTE_COMERCIAL]: {
    dashboard: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    leads: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    clientes: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    servicos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    visitas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    propostas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    vendas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    projetos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    execucoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    custos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    financeiro: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    compras: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    estoque: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    posvenda: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    logs: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    bi_consolidated: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    segmentos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: true, editar: true, deletar: false, exportar: false },
    sla_command: { visualizar: true, criar: true, editar: true, deletar: false, exportar: false },
    alertas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: false }
  },
  
  [UserRole.VENDEDOR]: {
    dashboard: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    leads: { visualizar: true, criar: true, editar: true, deletar: false, exportar: false },
    clientes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    servicos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    visitas: { visualizar: true, criar: true, editar: false, deletar: false, exportar: false },
    propostas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: false },
    vendas: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    projetos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    execucoes: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    custos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    financeiro: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    compras: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    estoque: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    posvenda: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    logs: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    bi_consolidated: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    segmentos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    sla_command: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    alertas: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false }
  },
  
  [UserRole.FINANCEIRO]: {
    dashboard: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    leads: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    clientes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    servicos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    visitas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    propostas: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    vendas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: true },
    projetos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    execucoes: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    custos: { visualizar: true, criar: false, editar: true, deletar: false, exportar: true },
    financeiro: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    compras: { visualizar: true, criar: false, editar: true, deletar: false, exportar: true },
    estoque: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    posvenda: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    logs: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    bi_consolidated: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    segmentos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    sla_command: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    alertas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: true }
  },

  [UserRole.COMPRAS]: {
    dashboard: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    leads: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    clientes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    servicos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    visitas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    propostas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    vendas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    projetos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    execucoes: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    custos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    financeiro: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    compras: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    estoque: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    posvenda: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    logs: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    bi_consolidated: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    segmentos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    sla_command: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    alertas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: false }
  },

  [UserRole.ESTOQUE]: {
    dashboard: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    leads: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    clientes: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    servicos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    visitas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    propostas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    vendas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    projetos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    execucoes: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    custos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    financeiro: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    compras: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    estoque: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    posvenda: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    logs: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    bi_consolidated: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    segmentos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    sla_command: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    alertas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: false }
  },

  [UserRole.GERENTE_OPERACIONAL]: {
    dashboard: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    leads: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    clientes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    servicos: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    visitas: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    propostas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    vendas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    projetos: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    execucoes: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    custos: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    financeiro: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    compras: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    estoque: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    posvenda: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    logs: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    bi_consolidated: { visualizar: true, criar: false, editar: false, deletar: false, exportar: true },
    segmentos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    sla_command: { visualizar: true, criar: true, editar: true, deletar: false, exportar: true },
    alertas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: true }
  },

  [UserRole.TECNICO]: {
    dashboard: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    leads: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    clientes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    servicos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    visitas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: false },
    propostas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    vendas: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    projetos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    execucoes: { visualizar: true, criar: false, editar: true, deletar: false, exportar: false },
    custos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    financeiro: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    compras: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    estoque: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    posvenda: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    logs: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    bi_consolidated: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    segmentos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    sla_command: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    alertas: { visualizar: true, criar: false, editar: true, deletar: false, exportar: false }
  },

  [UserRole.VISUALIZADOR]: {
    dashboard: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    leads: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    clientes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    servicos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    visitas: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    propostas: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    vendas: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    projetos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    execucoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    custos: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    financeiro: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    compras: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    estoque: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    posvenda: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    logs: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    bi_consolidated: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    segmentos: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    usuarios: { visualizar: false, criar: false, editar: false, deletar: false, exportar: false },
    notificacoes: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    sla_command: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false },
    alertas: { visualizar: true, criar: false, editar: false, deletar: false, exportar: false }
  },
};
